CREATE TABLE `Users` (
	`ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(12) NOT NULL COLLATE 'utf8mb4_general_ci',
	`posX` DOUBLE NOT NULL DEFAULT '0',
	`posY` DOUBLE NOT NULL DEFAULT '0',
	`posZ` DOUBLE NOT NULL DEFAULT '0',
	`dirX` DOUBLE NOT NULL DEFAULT '0',
	`dirY` DOUBLE NULL DEFAULT '0',
	PRIMARY KEY (`ID`) USING BTREE
)
COLLATE='utf8mb4_general_ci'